#!/usr/bin/env node
import { rolldown } from 'rolldown';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, '..');
const { version } = JSON.parse(readFileSync(resolve(pkgRoot, 'package.json'), 'utf8'));

const bundle = await rolldown({
  input: resolve(pkgRoot, 'src/uploader/worker/entry.ts'),
  platform: 'browser',
  resolve: {
    tsconfigFilename: resolve(pkgRoot, 'tsconfig.json'),
  },
});

const { output } = await bundle.generate({
  format: 'esm',
  minify: 'dce-only',
});

const code = output[0].code;

const workerScriptOut = resolve(pkgRoot, 'src/uploader/worker/worker-script.ts');
writeFileSync(
  workerScriptOut,
  `// Generated by scripts/build-worker.mjs at build time. Do not edit.\n// Run \`yarn workspace @spotify-confidence/csr-common build:worker\` to regenerate.\nexport const workerScript: string = ${JSON.stringify(code)};\n`,
);
console.log(`build-worker: wrote ${code.length} bytes to ${workerScriptOut}`);

const versionOut = resolve(pkgRoot, 'src/uploader/csr-version.ts');
writeFileSync(versionOut, `// Generated — do not edit.\nexport const CSR_VERSION = '${version}';\n`);
console.log(`build-worker: wrote csr-version ${version} to ${versionOut}`);
