#!/usr/bin/env node
import { rolldown } from 'rolldown';
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, '..');

const bundle = await rolldown({
  input: resolve(pkgRoot, 'src/uploader/worker/entry.ts'),
  platform: 'browser',
  resolve: {
    tsconfigFilename: resolve(pkgRoot, 'tsconfig.json'),
  },
});

const { output } = await bundle.generate({
  format: 'esm',
  minify: 'dce-only',
});

const code = output[0].code;
const out = resolve(pkgRoot, 'src/uploader/worker/worker-script.ts');
const body = `// Generated by scripts/build-worker.mjs at build time. Do not edit.
// Run \`yarn workspace @spotify-confidence/csr-common build:worker\` to regenerate.
export const workerScript: string = ${JSON.stringify(code)};
`;
writeFileSync(out, body);
console.log(`build-worker: wrote ${code.length} bytes to ${out}`);
