name: 'Setup Environment'
description: 'Setup Environment'
inputs:
  node-version:
    description: 'Node version to setup'
    required: false
    default: '20'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        scope: '@spotify-confidence'
    - name: Update npm
      shell: bash
      run: npm install -g npm@latest
    - name: Install dependencies
      shell: bash
      run: corepack enable && yarn install
