name: 'Setup Environment'
description: 'Setup Environment'
inputs:
  node-version:
    description: 'Node version to setup'
    required: false
    default: '22'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version: ${{ inputs.node-version }}
        scope: '@spotify-confidence'
    - name: Install dependencies
      shell: bash
      run: corepack enable && yarn install
