name: Amend Release with yarn.lock update

on:
  push:
    branches:
      - 'release-please**'

jobs:
  Amend-Release:
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.ref }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          scope: '@spotify-confidence'
      - name: Enable corepack
        shell: bash
        run: corepack enable
      - name: Fix constraints
        shell: bash
        run: yarn constraints --fix
      - name: Install dependencies
        shell: bash
        run: yarn install
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - name: Check for changes in yarn.lock
        id: git-check
        run: |
          git status
          git add -u
          git diff --staged --exit-code || echo "::set-output name=changed::true"
      - name: Commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config user.name "confidence-bot" && \
          git config user.email "confidence+bot@spotify.com" && \
          git add yarn.lock && \
          git commit -m "chore: auto update yarn.lock" && \
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
