name: Amend Release with yarn.lock update

on:
  workflow_dispatch:

jobs:
  Amend-Release:
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          scope: '@spotify-confidence'
      - name: Enable corepack
        shell: bash
        run: corepack enable
      - name: Fix constraints
        shell: bash
        run: yarn constraints --fix
      - name: Install dependencies
        shell: bash
        run: yarn install
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - run: yarn bundle
      - run: yarn lint
      - run: yarn format:check
      - run: yarn test
      - name: Commit and push changes changes in yarn.lock
        run: |
          git add -u
          if ! git diff --staged --stat --exit-code; then
            git config user.name "confidence-bot"
            git config user.email "confidence+bot@spotify.com"
            git add yarn.lock
            git commit -m "chore: auto update yarn.lock"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
