name: Amend Release with yarn.lock update

on:
  repository_dispatch:
    types: [release_amend_trigger]

jobs:
  Amend-Release:
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release-please--branches--main
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          scope: '@spotify-confidence'
      - name: Enable corepack
        shell: bash
        run: corepack enable
      - name: Fix constraints
        shell: bash
        run: yarn constraints --fix
      - name: Install dependencies
        shell: bash
        run: yarn install
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - name: Commit and push changes changes in yarn.lock
        run: |
          git add -u
          if ! git diff --staged --stat --exit-code; then
            git config user.name "confidence-bot"
            git config user.email "confidence+bot@spotify.com"
            git add yarn.lock
            git commit -m "chore: auto update yarn.lock"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger CI Build, Test, Lint Workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/spotify/confidence-sdk-js/dispatches \
          -d '{"event_type":"ci_validation_trigger", "client_payload": {}}'
