name: Build, Test, Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - id: setup-environment
        uses: ./.github/actions/setup
        with:
          node-version: '20'
      - run: yarn bundle
      - run: yarn lint
      - run: yarn format:check
      - run: yarn test

  Build-And-Test-CSR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - id: setup-environment
        uses: ./.github/actions/setup
        with:
          node-version: '20'
      - run: yarn build:csr
      - run: yarn lint:csr
      - run: yarn test:csr

  E2E-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - id: setup-environment
        uses: ./.github/actions/setup
        with:
          node-version: '20'
      - run: yarn bundle
      - run: yarn test:e2e
        env:
          CONFIDENCE_CLIENT_SECRET: ${{ secrets.CONFIDENCE_CLIENT_SECRET }}
